# physics
# Declaring variables and interface blocks
obj/physics.o           : obj/physics_vars.o obj/physics_interface.o 
# General dependencies
obj/physics_grav.o      : obj/physics.o
obj/physics_intertial.o : obj/physics.o 
obj/physics_main.o      : obj/physics.o obj/lusolver.o obj/io.o obj/driver.o
obj/physics_ns.o        : obj/physics.o 
onj/physics_wd.o        : obj/physics.o 
obj/physics_roche.o     : obj/physics.o 
