# physics
obj/physics_grav.o      : obj/physics.o
obj/physics_intertial.o : obj/physics.o 
obj/physics_main.o      : obj/physics.o 
obj/physics_ns.o        : obj/physics.o 
onj/physics_wd.o        : obj/physics.o 
obj/physics_roche.o     : obj/physics.o 
