# driver
obj/driver.o                     : obj/physics.o obj/driver_vars.o obj/driver_interface.o
obj/driver_abort.o               : obj/physics.o obj/component.o obj/io.o
obj/driver_ballistic.o           : obj/driver.o obj/component.o obj/ode.o 
obj/driver_data.o                : obj/driver.o obj/component.o obj/physics.o obj/io.o
obj/driver_func.o                : obj/driver.o obj/physics.o 
obj/driver_init.o                : obj/driver.o obj/io.o 
obj/driver_init_ballistic.o      : obj/driver.o obj/io.o obj/component.o obj/physics.o 
obj/driver_init_mdot.o           : obj/driver.o obj/io.o obj/component.o obj/physics.o obj/ode.o 
obj/driver_interrupt.o           : obj/driver.o obj/component.o 
obj/driver_interrupt_ballistic.o : obj/driver.o obj/component.o obj/io.o 
obj/driver_interrupt_mdot.o      : obj/driver.o obj/component.o obj/physics.o obj/io.o obj/ode.o
obj/driver_main.o                : obj/driver.o obj/io.o obj/eos.o
obj/driver_mdot.o                : obj/driver.o obj/component.o obj/physics.o obj/io.o obj/ode.o
obj/driver_post.o                : obj/driver.o obj/component.o obj/physics.o obj/io.o
obj/driver_reset.o               : obj/driver.o 
obj/driver_restore_defaults.o    : obj/driver.o obj/component.o 
obj/driver_stability.o           : obj/driver.o obj/io.o 
obj/driver_stability_1.o         : obj/driver.o obj/io.o obj/component.o obj/physics.o
obj/driver_stability_2.o         : obj/driver.o obj/io.o 
obj/driver_stability_3.o         : obj/driver.o obj/io.o obj/component.o obj/physics.o
obj/driver_stability_slaves.o    : obj/driver.o obj/io.o obj/component.o obj/physics.o
obj/driver_stop.o                : obj/driver.o obj/io.o
obj/driver_update.o              : obj/driver.o 
obj/driver_update_ballistic.o    : obj/driver.o obj/component.o obj/physics.o 
obj/driver_update_mdot.o         : obj/driver.o obj/component.o obj/physics.o obj/ode.o
obj/driver_update_tstep.o        : obj/driver.o obj/component.o obj/physics.o obj/ode.o obj/io.o
