# medium 
obj/medium_Lfunc.o : obj/medium.o 
obj/medium_calc.o  : obj/medium.o obj/physics.o obj/ode.o obj/IO.o
obj/medium_func.o  : obj/medium.o obj/physics.o
obj/medium_init.o  : obj/medium.o obj/physics.o obj/ode.o
obj/medium_main.o  : obj/medium.o obj/IO.o
