# EOS
obj/eos.o                : obj/eos_vars.o obj/eos_interface.o
onj/eos_init.o           : obj/eos.o
obj/eos_helmeos.o        : obj/eos_vector.o obj/eos_table_storage.o obj/eos_cons.o
obj/eos_helmholtz.o      : obj/eos_vector.o 
obj/eos_pretty_eos_out.o : obj/eos_vector.o 
obj/eos_read_helm_table.o: obj/eos_table_storage.o 
obj/eos_func.o           : obj/eos.o obj/driver.o 
obj/eos_root.o           : obj/eos.o obj/eos_vector.o obj/lusolver.o
obj/eos_root_table.o     : obj/eos_table_storage.o obj/eos_helmeos.o
