# component
obj/component.o               : obj/physics.o
obj/component_L1.o            : obj/component.o obj/driver.o obj/physics.o 
obj/component_eddington.o     : obj/component.o obj/driver.o obj/physics.o obj/IO.o
obj/component_envelope.o      : obj/component.o obj/driver.o obj/physics.o 
obj/component_evol.o          : obj/component.o obj/driver.o obj/physics.o 
obj/component_getvirtemp.o    : obj/physics.o 
obj/component_main.o          : obj/component.o obj/driver.o obj/IO.o
obj/component_mdot.o          : obj/component.o obj/driver.o obj/physics.o
obj/component_reset.o         : obj/component.o 
obj/component_stars.o         : obj/component.o obj/driver.o obj/physics.o obj/IO.o
obj/component_stream.o        : obj/component.o obj/physics.o
obj/component_system.o        : obj/component.o obj/driver.o obj/physics.o obj/IO.o
obj/component_system_slaves.o : obj/component.o obj/driver.o obj/physics.o obj/IO.o
obj/component_timescales.o    : obj/component.o obj/driver.o obj/physics.o
