# IO
obj/IO.o                    : obj/Mkracken.o 
obj/IO_data.o               : obj/IO.o 
obj/IO_file_handling.o      : obj/IO.o 
obj/IO_header.o             : obj/IO.o obj/driver.o obj/physics.o obj/component.o
obj/IO_log.o                : obj/IO.o
obj/IO_main.o               : obj/IO.o 
obj/IO_plot.o               : obj/IO.o obj/driver.o obj/physics.o obj/component.o 
obj/IO_write_header_sweep.o : obj/IO.o 
