# io
obj/io.o                    : obj/io_vars.o obj/io_interface.o obj/mkracken.o 
obj/io_interface.o          : obj/io_vars.o
obj/io_data.o               : obj/io.o 
obj/io_file_handling.o      : obj/io.o 
obj/io_header.o             : obj/io.o obj/driver.o obj/physics.o obj/component.o
obj/io_log.o                : obj/io.o
obj/io_main.o               : obj/io.o 
obj/io_plot.o               : obj/io.o obj/driver.o obj/physics.o obj/component.o 
obj/io_write_header_sweep.o : obj/io.o 
