# Compiler and flags
COMPILER       = gfortran
COMPILER_FLAGS = -Jmod -fdefault-real-8 -fbounds-check -fbacktrace -finit-real=nan -pedantic

# Executable name and general rule
.SUFFIXES:
.SUFFIXES: .f90 .o 

# General rule
obj/%.o     : %.f90 
	${COMPILER} ${COMPILER_FLAGS} -c -o $@ $<

