# Compile main program 
EXE    = 2STAR_
part   = main.o ${uobjs}
full   = ${patsubst %, obj/%, ${part}}
${EXE}: ${full}
	${COMPILER} -o $@ ${full}
#PST    = PAPER_
#part   = paper.o ${uobjs}
#full   = ${patsubst %, obj/%, ${part}}
#${PST}: ${full}
#	${COMPILER} -o $@ ${full}

# Cleanup
clean: 
	rm -f obj/*.o mod/*.mod ${EXE}
