# Compile main program 
EXE    = STAR_
part   = main.o ${uobjs}
full   = ${patsubst %, obj/%, ${part}}
${EXE}: ${full}
	${COMPILER} -o $@ ${full}
PST    = PAPER_
${PST}: ${full}
	${COMPILER} -o $@ ${full}

# Cleanup
clean: 
	rm -f obj/*.o mod/*.mod ${EXE}
